using UnityEngine;

[System.Serializable]
public class WorkSite
{
    public ResourceType resource;
    public int workersAssigned = 0;

    public int minResourcesPerWorker = 1, maxResourcesPerWorker = 2;
    public float minMoneyPerWorker = 0.25f, maxMoneyPerWorker = 0.5f;

    public int baseResourceUpgradeCost = 25, baseMoneyUpgradeCost = 25;
    public int resourceUpgradeCost = 25, moneyUpgradeCost = 25;

    private int _numResourceUpgrades = 0, _numMoneyUpgrades = 0;

    public int GenerateResources()
    {
        // Base resources generated is equal to the sum of the random resources generated by each worker
        int resourcesGenerated = 0;
        for (int i = 0; i < workersAssigned; i++)
            resourcesGenerated += Random.Range(minResourcesPerWorker, maxResourcesPerWorker + 1);
        
        // Round to int
        return Mathf.RoundToInt(resourcesGenerated);
    }

    public float GenerateMoney()
    {
        // Base money generated is equal to the sum of the random money generated by each worker
        // It is multiplied by 4 and converted to int when rolled randomly, then divided by 4 again to make sure each worker
        // only generates 0.25 or 0.5 money, so that the total money generated is always in increments of 0.25
        float moneyGenerated = 0f;
        for (int i = 0; i < workersAssigned; i++)
            moneyGenerated += Random.Range((int)(minMoneyPerWorker * 4), (int)(maxMoneyPerWorker * 4) + 1) / 4f;
        
        // Return without rounding, it is done on the total gold gained from all sites
        return moneyGenerated;
    }

    #region Upgrade
    public void UpgradeResourceGeneration()
    {
        if (ResourceManager.Instance != null && ResourceManager.Instance.GetNumResource(ResourceType.Money) >= resourceUpgradeCost)
        {
            // Lose money equal to resource upgrade cost
            ResourceManager.Instance.DecreaseResource(ResourceType.Money, resourceUpgradeCost);

            // Increment min/max resources generated and number of upgrades purchased
            minResourcesPerWorker++;
            maxResourcesPerWorker++;
            _numResourceUpgrades++;

            // Calculate cost of next upgrade up to 999
            resourceUpgradeCost = Mathf.Min(999,(int)(baseResourceUpgradeCost * Mathf.Pow(2, _numResourceUpgrades)));
            EventManager.OnUpgradePurchased();
        }
    }
    public void UpgradeMoneyGeneration()
    {
        if (ResourceManager.Instance != null && ResourceManager.Instance.GetNumResource(ResourceType.Money) >= moneyUpgradeCost)
        {
            // Lose money equal to resource upgrade cost
            ResourceManager.Instance.DecreaseResource(ResourceType.Money, moneyUpgradeCost);

            // Increment min/max money generated and number of upgrades purchased
            minMoneyPerWorker += 0.25f;
            maxMoneyPerWorker += 0.25f;
            _numMoneyUpgrades++;

            // Calculate cost of next upgrade up to 999 and call upgrade purchased event
            moneyUpgradeCost = Mathf.Min(999, (int)(baseMoneyUpgradeCost * Mathf.Pow(2, _numMoneyUpgrades)));
            EventManager.OnUpgradePurchased();
        }
    }
    #endregion

    #region Accessors
    // Generation
    public string GetResourceGenerationRange() => 
        $"{minResourcesPerWorker * workersAssigned}-{maxResourcesPerWorker * workersAssigned}";
    public string GetMoneyGenerationRange() => 
        $"{minMoneyPerWorker * workersAssigned:F2}-{maxMoneyPerWorker * workersAssigned:F2}";
    // Upgrade Text
    public string GetResourceUpgradeText() =>
        $"{minResourcesPerWorker}-{maxResourcesPerWorker}\n↓\n{minResourcesPerWorker + 1}-{maxResourcesPerWorker + 1}";
    public string GetMoneyUpgradeText() =>
        $"{minMoneyPerWorker:F2}-{maxMoneyPerWorker:F2}\n↓\n{minMoneyPerWorker + 0.25f:F2}-{maxMoneyPerWorker + 0.25f:F2}";
    // Upgrade Affordability
    public bool CanAffordResourceUpgrade()
    {
        if (ResourceManager.Instance != null)
            return ResourceManager.Instance.GetNumResource(ResourceType.Money) >= resourceUpgradeCost;
        else
            throw new System.NotImplementedException("Resource Manager is null.");
    }
    public bool CanAffordMoneyUpgrade()
    {
        if (ResourceManager.Instance != null)
            return ResourceManager.Instance.GetNumResource(ResourceType.Money) >= moneyUpgradeCost;
        else
            throw new System.NotImplementedException("Resource Manager is null.");
    }
    #endregion
}