using UnityEngine;

[System.Serializable]
public class WorkSite
{
    public int workersAssigned = 0;

    public int minResourcesPerWorker = 1, maxResourcesPerWorker = 2;
    public float minMoneyPerWorker = 0.25f, maxMoneyPerWorker = 0.5f;

    public float resourceUpgradeMultiplier = 1, moneyUpgradeMultiplier = 1;

    public int GenerateResources()
    {
        // Base resources generated is equal to the sum of the random resources generated by each worker
        int baseResourcesGenerated = 0;
        for (int i = 0; i < workersAssigned; i++)
            baseResourcesGenerated += Random.Range(minResourcesPerWorker, maxResourcesPerWorker + 1);
        
        // Apply upgrade multiplier and round
        return Mathf.RoundToInt(baseResourcesGenerated * resourceUpgradeMultiplier);
    }

    public float GenerateMoney()
    {
        // Base money generated is equal to the sum of the random money generated by each worker
        // It is multiplied by 4 and converted to int when rolled randomly, then divided by 4 again to make sure each worker
        // only generates 0.25 or 0.5 money, so that the total money generated is always in increments of 0.25
        float baseMoneyGenerated = 0;
        for (int i = 0; i < workersAssigned; i++)
            baseMoneyGenerated += Random.Range((int)(minMoneyPerWorker * 4), (int)(maxMoneyPerWorker * 4) + 1) / 4f;
        
        // Apply upgrade multiplier, rounding is done on the total gold gained from all sites
        return baseMoneyGenerated * moneyUpgradeMultiplier;
    }
}