using UnityEngine;

[System.Serializable]
public class WorkSite
{
    public int workersAssigned = 0;

    public int minResourcesPerWorker = 1, maxResourcesPerWorker = 2;
    public float minMoneyPerWorker = 0.25f, maxMoneyPerWorker = 0.5f;

    public float resourceUpgradeMultiplier = 1, moneyUpgradeMultiplier = 1;

    public int GenerateResources()
    {
        // Base resources generated is equal to the sum of the random resources generated by each worker
        int baseResourcesGenerated = 0;
        for (int i = 0; i < workersAssigned; i++)
            baseResourcesGenerated += Random.Range(minResourcesPerWorker, maxResourcesPerWorker + 1);
        
        // Apply upgrade multiplier and round
        return (int)Mathf.Round(baseResourcesGenerated * resourceUpgradeMultiplier);
    }

    public float GenerateMoney()
    {
        // Base money generated is equal to the sum of the random money generated by each worker
        float baseMoneyGenerated = 0;
        for (int i = 0; i < workersAssigned; i++)
            baseMoneyGenerated += Random.Range(minMoneyPerWorker, maxMoneyPerWorker + 1);
        
        // Apply upgrade multiplier and round
        return (int)Mathf.Round(baseMoneyGenerated * moneyUpgradeMultiplier);
    }
}